<a href="https://colab.research.google.com/github/Yx121/Machine-Learning-Basic/blob/main/Q-Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import random

In [2]:
rewards=np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,0,-1],
    [0,-1,-1,0,-1,-1],
    [-1,0,-1,-1,-1,-1]])

In [3]:
pd.DataFrame(rewards)

0  1  2  3  4    5
0 -1 -1 -1 -1  0   -1
1 -1 -1 -1  0 -1  100
2 -1 -1 -1  0 -1   -1
3 -1  0  0 -1  0   -1
4  0 -1 -1  0 -1   -1
5 -1  0 -1 -1 -1   -1

In [6]:
def initialize_q(m, n):
  return np.zeros((m,n))

q_matrix=initialize_q(6,6)
pd.DataFrame(q_matrix)

0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0

In [7]:
def set_initial_state(state=6):
  # set the initial state/room the agent starts at
    return np.random.randint(0,state)
  
def get_action(current_state, reward_matrix):
  # given a state, choose from the possible actions
    valid_actions=[]
    for action in enumerate(reward_matrix[current_state]):
        if action [1] !=-1:
            valid_actions+=[action[0]]
    return random.choice(valid_actions)

In [8]:
# To take some action, we need to know the current state

def take_action(current_state, reward_matrix, gamma, verbose=False):
    # take a single action
    action= get_action(current_state, reward_matrix)
    sa_reward= reward_matrix[current_state, action] # current_state-action reward
    ns_reward= max(q_matrix[action,])# next state-action reward
    q_current_state= sa_reward+(gamma*ns_reward)
    q_matrix[current_state, action]=q_current_state # matutes q_matrix
    new_state= action
    if verbose:
        print(q_matrix)
        print(f"Old State: {current_state} | New State: {new_state}\n\n")
        if new_state== 5:
            print(f"Agent has reached it's goal!")
    return new_state

In [9]:
def initialize_episode(reward_matrix, initial_state, gamma, verbose=False):
    # Runs 1 episode unitl the agent reaches its goal-state
    current_state = initial_state
    while True: # we dont use current_state==5, because it is possible to initialize in 5
        current_state= take_action(current_state, reward_matrix, gamma, verbose)
        if current_state ==5:
            break

def train_agent(iteration, reward_matrix, gamma, verbose=False):
    # Runs a given number of episodes then normalizs the matrix
    print("Training in progress...")
    for episode in range(iteration):
        initial_state =set_initial_state()
        initialize_episode(reward_matrix, initial_state, gamma, verbose)
    print("Training complete!")
    return q_matrix

def normalize_matrix(q_matrix):
    normalize_q=q_matrix/max(q_matrix[q_matrix.nonzero()])*100
    return normalize_q.astype(int)

In [11]:
# Test run of single episode....
gamma=0.1
initial_state=0
initial_action=get_action(initial_state, rewards)
initialize_episode(rewards, initial_state, gamma, True)
print(q_matrix)

[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Old State: 0 | New State: 4


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Old State: 4 | New State: 3


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Old State: 3 | New State: 4


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Old State: 4 | New State: 3


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.  

In [12]:
#Test run of full training
gamma=0.8
initial_state=set_initial_state()
initial_action=get_action(initial_state, rewards)
q_table=train_agent(2000, rewards, gamma, False)
print(pd.DataFrame(q_table))

Training in progress...
Training complete!
            0           1           2           3           4           5
0    0.000000    0.000000    0.000000    0.000000  142.222222    0.000000
1    0.000000    0.000000    0.000000  177.777778    0.000000  277.777778
2    0.000000    0.000000    0.000000  177.777778    0.000000    0.000000
3    0.000000  222.222222  142.222222    0.000000  142.222222    0.000000
4  113.777778    0.000000    0.000000  177.777778    0.000000    0.000000
5    0.000000  222.222222    0.000000    0.000000    0.000000    0.000000


In [13]:
pd.DataFrame(normalize_matrix(q_table))

0   1   2   3   4    5
0   0   0   0   0  51    0
1   0   0   0  64   0  100
2   0   0   0  64   0    0
3   0  80  51   0  51    0
4  40   0   0  64   0    0
5   0  80   0   0   0    0

In [16]:
def deploy_agent(initial_state, q_table):
  print("Start:", initial_state)
  state = initial_state
  steps = 0
  while True:
    steps += 1
    action = np.argmax(q_table[state, :])
    print(action)
    state = action
    if action == 5:
      print('Finished!')
      return steps

In [19]:
start_room = 0
steps = deploy_agent(start_room, q_table)
print("Number of Rooms/actions: ", steps)

Start: 0
4
3
1
5
Finished!
Number of Rooms/actions:  4
